"""initial schema

Revision ID: 6a72a06d0084
Revises:
Create Date: 2026-07-12 16:50:38.377566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6a72a06d0084"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("department", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("job", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hired_employees",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hired_employees_datetime"),
        "hired_employees",
        ["datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hired_employees_department_id"),
        "hired_employees",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hired_employees_job_id"), "hired_employees", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hired_employees_job_id"), table_name="hired_employees")
    op.drop_index(
        op.f("ix_hired_employees_department_id"), table_name="hired_employees"
    )
    op.drop_index(op.f("ix_hired_employees_datetime"), table_name="hired_employees")
    op.drop_table("hired_employees")
    op.drop_table("jobs")
    op.drop_table("departments")
    # ### end Alembic commands ###
